name: puzzle
version: 0.0.1
description: A minimal web app for the developer that doesn’t want to be confused by too much going on.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  markdown: any
  range: any
  script_inliner: '>=1.0.0 <2.0.0'
transformers:
- script_inliner
